default: &default
  github:
    organization: IIC2233
    organization_type: organization
    template_url: https://github.com/aaossa/IIC2233-student-template.git
    repository:
      name:
        # prefix + student_username + suffix
        prefix: ""
        suffix: "-iic2233-2017-2"
      description:
        # prefix + student_fullname + suffix
        prefix: "Repositorio para "
        suffix: ""
      private: false
      has_projects: false
      has_wiki: true
      member_permission: push
  home:
    title: Course Register
    course_description: >-
      Course description
    process_description: >-
      Process description

development:
  <<: *default
  github:
    organization: Syllabot
    organization_type: user

test:
  <<: *default

production:
  <<: *default
